// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// Values from android/app/google-services.json (shifa-doctor-staging)

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web. '
        'Run "flutterfire configure" and select web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAONE8lrUzgurI9h0zpw9TqersE-1V5J-8',
    appId: '1:55173524197:android:ddadc878f20da52792420c',
    messagingSenderId: '55173524197',
    projectId: 'shifa-doctor-staging',
    storageBucket: 'shifa-doctor-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSXfLL1xIcZVoj0xJZ05n_W81qTEFj6bc',
    appId: '1:55173524197:ios:91a17909836d42e292420c',
    messagingSenderId: '55173524197',
    projectId: 'shifa-doctor-staging',
    storageBucket: 'shifa-doctor-staging.firebasestorage.app',
    iosBundleId: 'uz.shifa.patient',
  );
}
